#https://www.gitpod.io/docs/introduction/getting-started

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup & Build
    before: pnpm install
    init: pnpm build
    command: pnpm dev
    
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-browser
    name: Template
    description: Demo WebPage
