#Idea by https://github.com/paulrberg/hardhat-template
name: Create

# The workflow will run only when `use this template` is used
on:
  create:

jobs:
  create:
    # We will only run this action when the repository isn't the template repository
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ !github.event.repository.is_template }}

    runs-on: ubuntu-20.04
    permissions: write-all

    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Update package.json"
        run: ./.github/scripts/change-package.sh "$GITHUB_REPOSITORY" "$GITHUB_REPOSITORY_OWNER"

      - name: "Update CODEOWNERS"
        run: ./.github/scripts/change-codeowners.sh "$GITHUB_REPOSITORY_OWNER"

      - name: "Update LICENSE.txt"
        run: ./.github/scripts/change-license.sh "$GITHUB_REPOSITORY_OWNER"

      - name: "Update SECURITY.md"
        run: ./.github/scripts/change-security.sh "$GITHUB_REPOSITORY" "$GITHUB_REPOSITORY_OWNER"

      - name: "Update README.md badges"
        run: ./.github/scripts/change-badges.sh "$GITHUB_REPOSITORY" "$GITHUB_REPOSITORY_OWNER"

      - name: "Add change name summary"
        run: |
          echo "## Commit results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
      - name: "Update commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat/initial-commit"
          commit_options: "--amend"
          push_options: "--force"
          skip_fetch: true

      - name: "Add commit summary"
        run: |
          echo "## Commit results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY