name: Snyk scan
on: 
  pull_request: {}
  push:
    branches:
      - main
      - master
      - qa
    paths:
      - .github/workflows/snyk.yml
  schedule:
    - cron: '0 0 * * 0'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}
  
jobs:
  security:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif