name: Test&Build
on:
  pull_request: {}
  push:
    branches:
      - main
      - master
      - qa
    paths:
      - .github/workflows/build.yml
  schedule:
    - cron: '0 0 * * 0'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "18.x"
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install dependencies
      run: pnpm install
    - name: Run test
      run: pnpm test
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "18.x"
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install dependencies
      run: pnpm install
    - name: Run test
      run: pnpm build